### ISSUE TITLE
Warn user when uploading images with invalid capture time

### ISSUE THREAD

**Issue by Egocentrix** [kickin-media/media-front-end#39]
Missing/incorrect capture time in EXIF metadata throws off the chronological sorting. Would be nice to show a warning when uploading photos with obviously wrong date/time (missing entirely, wrong year, that sort of thing)

**Comment by jeffreybakker** [comment]
Great idea!

EXIF data can be read during the upload process using the JS library below:
[https://github.com/exif-js/exif-js](https://github.com/exif-js/exif-js)

**Comment by jeffreybakker** [comment]
Also check for the exported color space, otherwise photos might be too green or blue
